import { LocationProvider } from "@/providers/LocationProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SupabaseProvider } from "@/providers/SupabaseProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "finds.club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <SupabaseProvider>
        <LocationProvider>
          <body className={inter.className}>{children}</body>
        </LocationProvider>
      </SupabaseProvider>
    </html>
  );
}
